
# This GHA workflow is triggered by a special comment to a particular GitHub
# Issue on the repository.

### TESTING ###
#
# To set up a BPAN Publishing Testing Environment:
#
# * Fork the 'bpan-org/bpan' repo to '<user>'
#
# * Copy this repo 'bpan-org/bpan-index' repo to '<user>/bpan-index'
#   * Note: You can't "fork" this repo because forks can't use GitHub Issues
# * Create a GitHub Issue #1 for the copied bpan-index repo
#
# * In a BPAN package repository clone directory, run these commands:
#   * `bpan config index.bpan.repo-url https://github.com/<user>/bpan-index`
#   * `bpan bump --publish`

on:
  # TODO Can we add more rules to limit the triggering of this workflow?
  # Should only be allowed by package owner.
  issue_comment:
    type: created

env:
  ### Show debug output in log:
  BPAN_INDEX_UPDATE_DEBUG: true

  gha_event_comment_url: ${{ github.event.comment.url }}
  gha_event_comment_body: ${{ github.event.comment.body }}
  gha_event_comment_reactions_url: ${{ github.event.comment.reactions.url }}
  gha_run_id: ${{ github.run_id }}
  gha_triggering_actor: ${{ github.triggering_actor }}


jobs:
  bpan-publish-job:
    if: github.event.comment.issue_url ==
        'https://api.github.com/repos/${{ github.repository_owner }}/bpan-index/issues/1'

    runs-on: ubuntu-22.04

    steps:

    - name: Install dependencies
      run: |
        sudo \
        DEBIAN_FRONTEND=noninteractive \
        apt-get install -y \
          pandoc \
          shellcheck \
        && true

    - name: Checkout this (bpan-index) repo
      uses: actions/checkout@v3

    - name: Checkout bpan repo nested in bpan-index dir
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository_owner }}/bpan
        path: bpan

    - name: Get request vars from the JSON hidden in the request comment
      uses: ./.github/actions/request-vars
      id: vars

    - name: Checkout the package repo publish commit, nested in bpan-index
      uses: actions/checkout@v3
      with:
        repository: ${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.repo }}
        ref: ${{ steps.vars.outputs.version }}
        path: package

    - name: Get the HTML url for the GHA job logs
      uses: Tiryoh/gha-jobid-action@v0
      id: jobs
      with:
        job_name: bpan-publish-job
        github_token: ${{ secrets.GITHUB_TOKEN }}


    ### Uncomment to debug in tmate:
    # - name: Debug environment with tmate
    #   uses: mxschmitt/action-tmate@v3
    # - run: exit 123


    # This step does all the work of package verification and index updating.
    # It uses the `bpan` command to do it, so the logic is separate from this
    # repository.
    # The same logic is used client side by `bpan publish` before it issues the
    # request, to ensure the publish will likely work.

    - name: Check the content and update the BPAN index (if ok)
      env:
        gha_job_html_url:     ${{ steps.jobs.outputs.html_url }}
        gha_request_package:  ${{ steps.vars.outputs.package }}
        gha_request_owner:    ${{ steps.vars.outputs.owner }}
        gha_request_repo:     ${{ steps.vars.outputs.repo }}
        gha_request_version:  ${{ steps.vars.outputs.version }}
        gha_request_commit:   ${{ steps.vars.outputs.commit }}

      run: |
        source bpan/.rc
        if [[ $BPAN_INDEX_UPDATE_DEBUG ]]; then
          set -x
          bpan -x publish 2>&1
        else
          bpan publish
        fi
